### PR TITLE
rebase to focal, update formatting, fix flag

### PR DESCRIPTION
**Pull request by aptalca**

### CODE REVIEW

**Comment by aptalca** [comment]
Don't merge yet, not working properly

**Comment by aptalca** [comment]
With beta 34, flags are respected, however paths are all treated as relative and not absolute: https://github.com/mregni/EmbyStat/issues/1801#issuecomment-1148661920

**Comment by aptalca** [comment]
Ready for merge now

**Review by thespad — APPROVED** [review]
LGTM

**Pull request merged**
